<?php


namespace Core\Factories\Classes\ModuleFactory;


use Core\Managers\Classes\HookManager\ClassHook;

class Module extends ClassHook
{
    public final function __construct()
    {
        parent::__construct(__CLASS__);
    }

    /*public function __call($szName, $lszArgs)
    {
        pre2(array($szName, $lszArgs));
        return parent::__call($szName, $lszArgs); // TODO: Change the autogenerated stub
    }*/
}